### ISSUE TITLE
Connect to CAS from R using SWAT when running a SAS-Viya AWS Setup

### ISSUE THREAD

**Issue by ALGW71** [aws-quickstart/quickstart-sas-viya#21]
Hi,

Is it possible to use the R SWAT package to access SAS when set up on an AWS platform? Where should we be running R from in order to do this?

If so, could you specify how we should run the CAS command - specifically in order to access the CAS controller which is in a private subnet.

Kind Regards,
Alex

**Comment by cohoga** [comment]
Alex, 
I did this recently by creating a new VM with R Studio installed in my Public Subnet with a Public IP.  Then allow inbound traffic into the ViyaSecuirtyGroup from the security group you created for R Studio - port 5570 at a minimum.  I would also copy the /etc/hosts file from the Viya machines to the R Studio client.

**Comment by ALGW71** [comment]
Hi Connor,
Many thanks for this, with a bit of tweaking we got it up and running now - doing what you suggested except we went in through port 8777 via HTTPS from a VM that had the right permissions to access the private subnet. Connected and ready to go!
Many thanks for your reply.
Kind Regards,
Alex
