### ISSUE TITLE
AWS Deployment fails

### ISSUE THREAD

**Issue by rparraca** [aws-quickstart/quickstart-sas-viya#22]
I have tried, several times, to deploy this in two different AWS accounts (to make sure it wasn't a quota problem) but the deployment has failed every single time.

- My quotas are okay
- I have the license file, placed in S3 as indicated (the validation process goes through)

So far, no luck and I can't quite figure out why the deployment fails. This is the place where it fails: 

Embedded stack arn:aws:cloudformation:us-east-1:200116411579:stack/SAS-Viya-SASViyaStack-1839K2R0R81XC/f003fd30-f3a8-11ea-b531-0a90b7832da7 was not successfully created: The following resource(s) failed to create: [StackComplete].

**Comment by mayankcp** [comment]
If you are using the Viya Mirror then update it with the latest packages that should fix the problem.

**Comment by vsnyc** [comment]
Could you retry and open a new issue if you discover any new problems, we identified a couple of problems that have been addressed in PR #27 and #28
