### ISSUE TITLE
GetBucket Location, License info ERROR on Cloudformation

### ISSUE THREAD

**Issue by Sinovuyo96** [aws-quickstart/quickstart-sas-viya#23]
I have got an error on my Stack, it says 'No location found to host bucket, make sure GetBucketLocation policy is specified'. I am trying to deploy a file for SAS Viya for SAS Visual Statistics, visual analytics, SAS Data Preparation,  , SAS Visual Data Mining and Machine Learning.The file that contains the data is on S3 bucket

**Comment by vsnyc** [comment]
This is fixed, please retry. See https://github.com/aws-quickstart/quickstart-sas-viya/issues/24#issuecomment-721474894 for an explanation.
