### ISSUE TITLE
Viya Quick start fails with error 

### ISSUE THREAD

**Issue by esshab** [aws-quickstart/quickstart-sas-viya#29]
Embedded stack arn:aws:cloudformation:us-east-2:617292774228:stack/ViyaTestNov03-001-SASViyaStack-CJSRYZSD0FAV/50602060-1de7-11eb-bfad-06a590253d7a was not successfully created: The following resource(s) failed to create: [LicenseInfo, StackComplete].

**Comment by vsnyc** [comment]
Thanks for opening this. We've discovered an issue that wasn't caught in our CI. I am testing a fix.

**Comment by vsnyc** [comment]
This is addressed, see https://github.com/aws-quickstart/quickstart-sas-viya/issues/24#issuecomment-721474894 for an explanation.
