### ISSUE TITLE
Fails to Attach EIP to Ansible Controller

### ISSUE THREAD

**Issue by justinwilson411** [aws-quickstart/quickstart-sas-viya#31]
The template for deploying into an existing VPC seems to have an issue that prevents the full deployment from occurring.  The Ansible instance is created, however, the EIP is not associated meaning the box has no public IP and thus fails to download the required packages in the User Data scripts.  

If I associate the EIP manually and SSH to the Ansible box I can manually execute the steps in the User Data scripts, but not before manually associating the EIP.  I have tried many different approaches today to get around this, however, none have been successful.   Short of manually processing the steps I am not sure where to go from here if I want to use this quickstart.

**Comment by sasgwb** [comment]
Is the existing VPC configured as specified in the Deployment Guide? (https://aws-quickstart.s3.amazonaws.com/quickstart-sas-viya/doc/sas-viya-on-the-aws-cloud.pdf):

_If you’re deploying SAS Viya into an existing VPC, make sure that your VPC has one public subnet and one private subnet in the same Availability Zones for the SAS Viya VM instances. These subnets require NAT gateways or NAT instances in their route tables to allow the instances to download packages and software without exposing them to the internet._

**Comment by justinwilson411** [comment]
> _If you’re deploying SAS Viya into an existing VPC, make sure that your VPC has one public subnet and one private subnet in the same Availability Zones for the SAS Viya VM instances. These subnets require NAT gateways or NAT instances in their route tables to allow the instances to download packages and software without exposing them to the internet._

I do have a public and a private.  The public Subnet routes out through an Internet Gateway and the private goes out through a NAT gateway.  The issue is definitely related to Ansible not being able to download packages due to not having an EIP assigned to it.  I see the deployment has allocated an EIP, but it does not associate during the process.  

I feel like I might be missing something here, but I cannot be sure.  Our environment very closely resembles the one in the diagrams, aside from our other resources.

**Comment by sasgwb** [comment]
Ok. I suspect this issue may be due to your specific VPC configuration - our tests with our own existing VPC are successful. Contact me at the email listed on my profile and I'll try to provide some assistance.

**Comment by justinwilson411** [comment]
Sounds good.  Will do and closing this issue as it is obviously my environment.
